Repository tabuckner/broskichat, pull requests merged in 2018-08, with the labels that each got.

#10 Home Page v1
  broskichat-app/src/App.jsx
  broskichat-app/src/Components/Home/Hero/Hero.jsx
  broskichat-app/src/Components/Home/Home.jsx
  broskichat-app/src/Components/Home/Marketing/Marketing.jsx
  broskichat-app/src/Components/Home/Marketing/Point/Point.jsx
  broskichat-app/src/Components/Home/img/community.png
  broskichat-app/src/Components/Home/img/multi-device.png
  broskichat-app/src/Components/Home/img/typing.png
  broskichat-app/src/Components/Partials/Header.jsx
Labels: enhancement

#12 Footerbranch
  broskichat-app/src/App.css
  broskichat-app/src/App.jsx
  broskichat-app/src/App.test.js
  broskichat-app/src/Components/Partials/Copyright/Copyright.jsx
  broskichat-app/src/Components/Partials/Footer.jsx
  broskichat-app/src/Components/Partials/PreFooter/PreFooter.jsx
  broskichat-app/src/index.css
Labels: enhancement

#15 34 - CodeCov
  .travis.yml
  broskichat-app/codecov.yaml
  broskichat-app/package.json
Labels: enhancement

#13 38 - Unit Tests and Cleanup
  broskichat-app/package.json
  broskichat-app/src/App.css
  broskichat-app/src/App.jsx
  broskichat-app/src/App.test.js
  broskichat-app/src/Components/Home/Hero/Hero.test.js
  broskichat-app/src/Components/Home/Home.test.js
  broskichat-app/src/Components/Home/Marketing/Marketing.test.js
  broskichat-app/src/Components/Home/Marketing/Point/Point.jsx
  broskichat-app/src/Components/Home/Marketing/Point/Point.test.js
  broskichat-app/src/Components/Partials/Copyright/Copyright.jsx
  broskichat-app/src/Components/Partials/Copyright/Copyright.test.js
  broskichat-app/src/Components/Partials/Footer.test.js
  broskichat-app/src/Components/Partials/Header.test.js
  broskichat-app/src/Components/Partials/PreFooter/PreFooter.test.js
  broskichat-app/src/setupTests.js
  broskichat-app/yarn.lock
Labels: TASK

#16 Integrated header
  broskichat-app/src/Components/Partials/Header.jsx
  broskichat-app/src/Components/Partials/Header.test.js
Labels: enhancement

#19 [RC-0.0.1]
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  README.md
  broskichat-app/.github/PULL_REQUEST_TEMPLATE.md
  broskichat-app/.gitignore
  broskichat-app/codecov.yaml
  broskichat-app/package.json
  broskichat-app/src/App.css
  broskichat-app/src/App.jsx
  broskichat-app/src/App.test.js
  broskichat-app/src/Components/Home/Hero/Hero.jsx
  broskichat-app/src/Components/Home/Hero/Hero.test.js
  broskichat-app/src/Components/Home/Home.jsx
  broskichat-app/src/Components/Home/Home.test.js
  broskichat-app/src/Components/Home/Marketing/Marketing.jsx
  broskichat-app/src/Components/Home/Marketing/Marketing.test.js
  broskichat-app/src/Components/Home/Marketing/Point/Point.jsx
  broskichat-app/src/Components/Home/Marketing/Point/Point.test.js
  broskichat-app/src/Components/Home/img/community.png
  broskichat-app/src/Components/Home/img/multi-device.png
  broskichat-app/src/Components/Home/img/typing.png
  broskichat-app/src/Components/Partials/Copyright/Copyright.jsx
  broskichat-app/src/Components/Partials/Copyright/Copyright.test.js
  broskichat-app/src/Components/Partials/Footer.jsx
  broskichat-app/src/Components/Partials/Footer.test.js
  broskichat-app/src/Components/Partials/Header.jsx
  broskichat-app/src/Components/Partials/Header.test.js
  broskichat-app/src/Components/Partials/PreFooter/PreFooter.jsx
  broskichat-app/src/Components/Partials/PreFooter/PreFooter.test.js
  broskichat-app/src/index.css
  broskichat-app/src/index.js
  broskichat-app/src/setupTests.js
  broskichat-app/yarn.lock
Labels: Release Candidate

#18 User auth
  broskichat-api/common/models/chat-user.js
  broskichat-api/common/models/chat-user.json
  broskichat-api/server/model-config.json
Labels: enhancement

#20 Update .travis.yml
  .travis.yml
  README.md
Labels: enhancement

#17 38 - CodeCov fixes
  broskichat-app/codecov.yaml
  broskichat-app/package.json
Labels: bug

#21 About page
  .DS_Store
  broskichat-app/src/App.jsx
  broskichat-app/src/Components/About/About.jsx
  broskichat-app/src/Components/About/software.png
Labels: enhancement

#23 Integrated react-router-dom
  broskichat-app/package.json
  broskichat-app/src/App.jsx
  broskichat-app/src/Components/Partials/Header.jsx
  broskichat-app/yarn.lock
Labels: enhancement

#24 Integrate socketio fe
  broskichat-api/package.json
  broskichat-api/server/server.js
  broskichat-api/yarn.lock
  broskichat-app/package.json
  broskichat-app/src/App.jsx
  broskichat-app/src/Components/Chat/Chat.jsx
  broskichat-app/src/Components/Partials/Header.jsx
  broskichat-app/src/shared/Global/sockets/events.js
  broskichat-app/yarn.lock
Labels: enhancement

#27 Revised marketing cards
  broskichat-app/src/Components/Home/Marketing/Point/Point.jsx
  broskichat-app/src/Components/Home/img/community.png
  broskichat-app/src/Components/Home/img/multi-device.png
  broskichat-app/src/Components/Home/img/typing.png
Labels: bug

#25 Integrate socketio
  broskichat-api/client/index.html
  broskichat-api/package.json
  broskichat-api/server/boot/root.js
  broskichat-api/server/middleware.json
  broskichat-api/server/server.js
  broskichat-api/yarn.lock
  broskichat-app/package.json
  broskichat-app/src/App.jsx
  broskichat-app/src/Components/Chat/Chat.jsx
  broskichat-app/src/Components/Partials/Header.jsx
  broskichat-app/src/shared/Global/sockets/events.js
  broskichat-app/yarn.lock
Labels: enhancement

#28 Added simple login component
  broskichat-app/src/App.jsx
  broskichat-app/src/Components/Login/Login.jsx
  broskichat-app/src/Components/Partials/Header.jsx
  broskichat-app/src/Components/Shared/BInput.jsx
Labels: enhancement

#31 Quickfix for router.
  broskichat-app/src/App.jsx
Labels: bug

#32 Clean up routing.
  broskichat-app/src/App.jsx
Labels: enhancement
